# Generated by Django 3.0.7 on 2020-11-01 08:52

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Op_info',
            fields=[
                ('operator_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('agency_name', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=30)),
                ('contact_person_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('document_name', models.CharField(max_length=20, null=True)),
                ('document_no', models.PositiveIntegerField(null=True)),
                ('recovery_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Op_request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('agency_name', models.CharField(max_length=30)),
                ('agency_email', models.EmailField(max_length=250)),
                ('message', models.CharField(max_length=100)),
                ('status', models.BooleanField(null=True)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(blank=True, max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_info',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('no_of_tickets', models.PositiveIntegerField()),
                ('vehicle_name', models.CharField(max_length=30)),
                ('route_starting_point', models.CharField(blank=True, max_length=30)),
                ('route_destination_point', models.CharField(blank=True, max_length=30)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Op_info')),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Vehicle_info')),
                ('sunday', models.BooleanField(default=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Vehicle_info')),
                ('boarding_point1', models.CharField(max_length=15)),
                ('boarding_point2', models.CharField(max_length=15, null=True)),
                ('boarding_point3', models.CharField(blank=True, max_length=15, null=True)),
                ('boarding_point4', models.CharField(blank=True, max_length=15, null=True)),
                ('boarding_point5', models.CharField(blank=True, max_length=15, null=True)),
                ('dropping_point1', models.CharField(max_length=15)),
                ('dropping_point2', models.CharField(max_length=15, null=True)),
                ('dropping_point3', models.CharField(blank=True, max_length=15, null=True)),
                ('dropping_point4', models.CharField(blank=True, max_length=15, null=True)),
                ('dropping_point5', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_time_info',
            fields=[
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Vehicle_info')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('fare', models.PositiveIntegerField()),
                ('driver_phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
    ]
