# Generated by Django 3.0.7 on 2020-11-03 10:31

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='op_info',
            name='contact_person_no',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='op_request',
            name='contact_no',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='vehicle_time_info',
            name='driver_phone_no',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
