# Generated by Django 3.0.7 on 2020-11-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201103_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='op_info',
            name='document_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
