# Generated by Django 3.0.7 on 2020-11-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201106_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_info',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Op_info'),
        ),
    ]
